Uplift to use Kafka 3.2.0 (#51)
* Uplift to use Kafka 3.2.0

Squashed commit of the following:

commit efde9f5c804e70b567081a9d329793085926dddb
Author: Matt Garlock <matt.garlock@oracle.com>
Date:   Thu Feb 2 17:47:18 2023 -0600

    Uplift deprecated committed method calls

commit dbc287ce3dcf3855cee0606f002b7acd3610e62f
Author: Matt Garlock <matt.garlock@oracle.com>
Date:   Thu Feb 2 17:01:52 2023 -0600

    Building successfully.

commit 760538106b114e401d21b56de1b35c8df5bc9c8c
Author: Matt Garlock <matt.garlock@oracle.com>
Date:   Thu Feb 2 15:34:48 2023 -0600

    formatting fix

commit d24bb36d8903fdbfa69bd7954c99342b9200551c
Merge: 07418eb 116515a
Author: matt-garlock <123006133+matt-garlock@users.noreply.github.com>
Date:   Thu Feb 2 13:45:33 2023 -0600

    Merge pull request #1 from tejkiran/ODH-uplift

    fix to use quorum test harness zk port to spin up kafka cluster

commit 116515a295650f9ae21038c8074156bc022658f4
Author: tm053662 <tej.meka@cerner.com>
Date:   Thu Feb 2 13:10:54 2023 -0600

    fix to use quorum test harness zk port to spin up kafka cluster

commit 07418ebc3a14460316570d9e47688e8435d7c963
Author: Matt Garlock <matt.garlock@oracle.com>
Date:   Thu Feb 2 11:20:38 2023 -0600

    Add kafka-clients test classifier dependency

commit 1b6761cb41af0200525500c2fe78eebe0dade9d9
Author: Matt Garlock <matt.garlock@oracle.com>
Date:   Thu Feb 2 10:41:34 2023 -0600

    Fix Processing Partition Test

commit 0d65facf4f717e50d390bf0608411d3ec7712386
Author: Matt Garlock <matt.garlock@oracle.com>
Date:   Thu Feb 2 09:02:21 2023 -0600

    Failing with NoClassDefFoundError org/apache/kafka/test/TestUtils

* Remove wildcard imports

* remove kafka-streams from dependency management

* Exclude special characters from strings used for topics

* Initialize topicNames with stream

* Add specificity to matchers used in ProcessingPartitionTest

* Update project version

* Switch KafkaConsumer back to Consumer where applicable.  Remove zkclient dependency management

* Update versions in maven dependency examples

* Java doc updates

* Update documentation link versions in readme

* Add migration guide